In [1]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)

In [4]:
np.array(li*3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [5]:
print(arr.data)
print(arr.shape)

(5,)


In [6]:
print(arr.dtype)
print(arr.strides)

int32
(4,)


In [2]:
a = np.empty(4, dtype = int)
print(a)

[ 388918497 1248115995  855138005  983402787]


In [4]:
a = np.random.randint(0,10, (4,4))
a

array([[9, 7, 4, 7],
       [7, 0, 8, 7],
       [2, 1, 4, 8],
       [0, 8, 6, 6]])

In [31]:
np.random.rand(1)

array([0.78269089])

Problem Statement:

Create an array with values ranging consecutively from 9 to 49 (both inclusive).

In [33]:
a= np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [34]:
for i in a:
    print(i, end = ' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

### Identity Matrix

Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).

In [36]:
import numpy as np

np.eye(5,6,  dtype= int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

#### Cut the Rope

Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

In [38]:
a = np.linspace(0,5,9, dtype = float)
for i in np.round(a, 2):
    print(i)

0.0
0.62
1.25
1.88
2.5
3.12
3.75
4.38
5.0
