In [1]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)

In [4]:
np.array(li*3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [5]:
print(arr.data)
print(arr.shape)

(5,)


In [6]:
print(arr.dtype)
print(arr.strides)

int32
(4,)


In [2]:
a = np.empty(4, dtype = int)
print(a)

[ 388918497 1248115995  855138005  983402787]


In [4]:
a = np.random.randint(0,10, (4,4))
a

array([[9, 7, 4, 7],
       [7, 0, 8, 7],
       [2, 1, 4, 8],
       [0, 8, 6, 6]])

In [31]:
np.random.rand(1)

array([0.78269089])

Problem Statement:

Create an array with values ranging consecutively from 9 to 49 (both inclusive).

In [33]:
a= np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [34]:
for i in a:
    print(i, end = ' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

### Identity Matrix

Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).

In [36]:
import numpy as np

np.eye(5,6,  dtype= int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

#### Cut the Rope

Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

In [49]:
a = np.linspace(0,5,10, dtype = float)
a = np.round(a, 2)
for i in a[1:-1]:
    print(i)

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [48]:
a[1:-1]

array([0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44])

In [50]:
type((4))

int

In [51]:
type((4,))

tuple

#### Print Elements

Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

In [52]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

In [54]:
input_

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
# a = input_[2,:3]
# # print(list(a))
# for i in list(a):
#     print(i, end = ' ')
# print()

a = input_[1:, 3]
for i in list(a):
    print(i, end = ' ')
print()
    
    
a = input_[2:, ].reshape(1,-1)
for i in a[0]:
    print(i, end = ' ')
print()

a = input_[1:3, 1:3].reshape(1,-1)
for i in a[0]:
    print(i, end = ' ')
print()

9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [97]:
a = input_[1:3, 1:3].reshape(1,-1)
a[0]

array([ 7,  8, 12, 13])

In [ ]:
[[ 7,  8, 12, 13], 
[ 7,  8, 12, 13]]

In [62]:
for i in input_[1:3, 1:3]:
    print(i)

[7 8]
[12 13]


In [55]:
input_[2,:3]

array([11, 12, 13])

In [56]:
input_[1:, 3]

array([ 9, 14, 19])

In [57]:
input_[2:, ]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Non-Zero elements

Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [99]:
a = [1,2,0,0,4,0]

a = np.array(a)
a

array([1, 2, 0, 0, 4, 0])

In [102]:
np.where(a>0)

(array([0, 1, 4], dtype=int64),)