In [1]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)

In [4]:
np.array(li*3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [5]:
print(arr.data)
print(arr.shape)

(5,)


In [6]:
print(arr.dtype)
print(arr.strides)

int32
(4,)


In [2]:
a = np.empty(4, dtype = int)
print(a)

[ 388918497 1248115995  855138005  983402787]


In [4]:
a = np.random.randint(0,10, (4,4))
a

array([[9, 7, 4, 7],
       [7, 0, 8, 7],
       [2, 1, 4, 8],
       [0, 8, 6, 6]])

In [31]:
np.random.rand(1)

array([0.78269089])

Problem Statement:

Create an array with values ranging consecutively from 9 to 49 (both inclusive).

In [33]:
a= np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [34]:
for i in a:
    print(i, end = ' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

### Identity Matrix

Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).

In [36]:
import numpy as np

np.eye(5,6,  dtype= int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

#### Cut the Rope

Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

In [49]:
a = np.linspace(0,5,10, dtype = float)
a = np.round(a, 2)
for i in a[1:-1]:
    print(i)

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [48]:
a[1:-1]

array([0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44])

In [50]:
type((4))

int

In [51]:
type((4,))

tuple

#### Print Elements

Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

In [52]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

In [54]:
input_

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
# a = input_[2,:3]
# # print(list(a))
# for i in list(a):
#     print(i, end = ' ')
# print()

a = input_[1:, 3]
for i in list(a):
    print(i, end = ' ')
print()
    
    
a = input_[2:, ].reshape(1,-1)
for i in a[0]:
    print(i, end = ' ')
print()

a = input_[1:3, 1:3].reshape(1,-1)
for i in a[0]:
    print(i, end = ' ')
print()

9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


In [97]:
a = input_[1:3, 1:3].reshape(1,-1)
a[0]

array([ 7,  8, 12, 13])

In [ ]:
[[ 7,  8, 12, 13], 
[ 7,  8, 12, 13]]

In [62]:
for i in input_[1:3, 1:3]:
    print(i)

[7 8]
[12 13]


In [55]:
input_[2,:3]

array([11, 12, 13])

In [56]:
input_[1:, 3]

array([ 9, 14, 19])

In [57]:
input_[2:, ]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Non-Zero elements

Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [99]:
a = [1,2,0,0,4,0]

a = np.array(a)
a

array([1, 2, 0, 0, 4, 0])

In [102]:
np.where(a>0)

(array([0, 1, 4], dtype=int64),)

#### Replace Max

Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array

In [1]:
import numpy as np

a = [11, 2, 13, 4, 15, 6, 27, 8, 19]

arr = np.array(a)
arr

array([11,  2, 13,  4, 15,  6, 27,  8, 19])

In [6]:
ind = arr.argmax()
arr[ind] = 0

In [8]:
ind

6

#### Negate Elements

Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [1]:
import numpy as np

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

arr = np.array(a)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
cond = np.logical_and((arr<= 8) , (arr>=3))
cond

array([False, False,  True,  True,  True,  True,  True,  True, False,
       False])

In [5]:
arr[cond]*=-1

In [6]:
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### Height

Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.

In [7]:
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

In [12]:
cond = height>155
cond

array([ True, False,  True,  True, False,  True, False, False, False,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True, False])

In [11]:
height[cond]

array([156, 180, 162, 157, 158, 179, 182, 183, 159, 160, 172])

In [13]:
age[cond]

array([15, 19, 20, 21, 22, 23, 16, 18, 20, 15, 17])

In [14]:
ind = np.where(height>155)
ind # list of index

(array([ 0,  2,  3,  5, 10, 11, 13, 14, 16, 17, 18], dtype=int64),)

In [21]:
for i in ind[0]:
    print(age[i], height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


#### Sort by column

Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1

In [35]:
import numpy as np
arr2D = np.array([[21, 20, 19, 18, 17],
                [16, 15, 14, 13, 12],
                [11, 10, 9,  8,  7],
                [ 6,  5,  4,  3,  2]])

# NOTE

In [37]:
arr2D[arr2D[:,2].argsort()]

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [23]:
columnIndex = 2
sortedArr = arr2D[arr2D[:,columnIndex].argsort()]

In [24]:
sortedArr

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

### Killed in USA

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :

Find value of killed column only where country == ‘United States’?

Print 0 in place of missing values.

Print count of Killed as integer value.

In [51]:
## Open and read data file as specified in the question
## Print the required output in given format

import csv

file_obj = open('data/numpy/terrorismData.csv')
file_data = csv.DictReader(file_obj, skipinitialspace = True)
# file_list = list(file_data)

for row in file_data:
    if row['Country']=='United States':
        print(row['Killed'])


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0


UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6235: character maps to <undefined>